### PR TITLE
feat: watch teleport slot change

### PR DESCRIPTION
**Pull request by jackiotyu**
it may improve this case: the slot element is change by v-if

### CODE REVIEW

**Comment by Mechazawa** [comment]
Looks good, I'll test this during my weekend 👍

**Comment by eriksaulnier** [comment]
@Mechazawa any chance of getting this feature merged and released?

**Comment by Mechazawa** [comment]
Sorry, completely forgot. Looks good

**Comment by eriksaulnier** [comment]
@Mechazawa it looks like this PR ended up breaking the teleport component a bit :( maybe best to revert? unless you or @jackiotyu can figure out what is going on.

**Comment by jackiotyu** [comment]
@eriksaulnier 
image
image
version 1.1.0 missing dist folder.

**Comment by jackiotyu** [comment]
https://github.com/Mechazawa/vue2-teleport/blob/6bb4ea5f4e26e294e9e5948a8604830105213f0d/src/Teleport.vue#L148
My mistake, this line of code caused the nodes to not synchronize destruction after the teleport component was destroyed. 
It still works fine after removing it.

**Pull request merged**
